{
 "title": "App logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Loyalty-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{swarm_service=\"services_loyalty-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Payment-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{swarm_service=\"services_payment-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Report-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{swarm_service=\"services_report-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Hotel-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{swarm_service=\"services_hotel-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Session-service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{service_name=\"services_session-service.1.jr4b1pz8rhugu2rq8bthtqfti\"} |= ``"
    }
   ]
  },
  {
   "title": "Gateway-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{service_name=\"services_gateway-service.1.l0cv8m7rvjld8fz1bkuzgwa4m\"} |= ``"
    }
   ]
  },
  {
   "title": "Booking-service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{service_name=\"services_booking-service.1.1cago55y60hn2qzz2dtphz4ed\"} |= ``"
    }
   ]
  }
 ]
}