{
 "title": "Apps metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "number of messages processed in rabbitmq",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_consumed_total{job=\"report-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of messages sent to rabbitmq",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_published_total{job=\"booking-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of user authorization requests received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"session-service\",uri=\"/api/v1/auth/authorize\",outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of bookings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"booking-service\",uri=\"/api/v1/booking\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of requests received at the gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"gateway-service\"})\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}