version: "3.8"

services:
  loki:
    image: grafana/loki:2.8.0
    ports:
      - 3100:3100
    networks:
     - public

  prometheus:
    ports:
      - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-admin-api
    - --web.enable-lifecycle
    - --web.listen-address=0.0.0.0:9090
    - --storage.tsdb.retention.time=30d
    image: prom/prometheus:v2.50.0
    user: root
    networks:
     - public
    volumes:
    - /opt/prometheus/data:/prometheus
    - /opt/prometheus/configs:/etc/prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8080:8080
    deploy:
      mode: global
    networks:
     - public
    command: -docker_only
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    networks:
      - public          

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    networks:
      - public

  grafana:
    restart: always
    image: grafana/grafana:10.2.4-ubuntu
    networks:
      - public
    ports:
     - '3000:3000'
    volumes:
      - /opt/grafana/config:/etc/grafana
      - /opt/grafana/storage:/var/lib/grafana
      - /opt/grafana/logs:/var/log/grafana
      - /opt/grafana/datasources:/etc/grafana/provisioning/datasources
    user: "0"

  alertmanager:
    command:
    - --web.listen-address=0.0.0.0:9093
    - --config.file=/etc/alertmanager/config.yml
    - --log.level=debug
    image: prom/alertmanager:v0.26.0
    networks:
      - public
    ports:
      - 9093:9093
    volumes:
      - ./config.yml:/etc/alertmanager/config.yml

networks:
  public:
    external: true